[tool.poetry]
name = "quam_libs"
version = "0.1.0"
description = "QuAM Components for Quantum Control"
readme = "README.md"
authors = ["Dean Poulos <dean.poulos@quantum-machines.co>"]
license = "BSD-3-Clause"
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
quam = "*"
qualang-tools = { git = "https://github.com/qua-platform/py-qua-tools.git", rev = "a7c126559a4cac2a824b8ca7ec7f508ef9f89aa2" }
xarray = "*"
lmfit = "*"
qiskit-experiments = "*"
tqdm = "*"
qualibrate = "*"
qm-qua = "1.2.1a2"
cirq = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
