[tool.poetry]
name = "qua-libs"
version = "0.1.0"
description = "A collection of examples to be used with QUA language"
authors = ["Tal Shani <tal@quantum-machines.co>"]
license = "BSD"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
Pillow = "^9.0.1"
bokeh = "^2.4.2"
cryptography = "^36.0.1"
Jinja2 = "^3.0.3"
lxml = "^4.7.1"
pikepdf = "^4.2.0"
websockets = "^10.1"
ipykernel = "^6.27.1"
sqlalchemy = "^1.4.50"
colorama = "^0.4.3"
matplotlib = "^3.8.2"
numpy = "^1.26.2"
pandas = "^2.1.4"
scipy = "^1.11.4"
seaborn = "^0.13.1"
scikit-learn = "^1.3.2"
networkx = "^2.5.1"
h5py = "^3.2.1"
cma = "^3.0.3"
PyVISA = "^1.11.3"
qcodes = "^0.40.0"
qm-qua = "1.1.7"
cirq = "^1.3.0"
qutip = "^4.7.3"
setuptools = "^69.5.1"
dataclasses-json = "^0.6.5"
jax = "^0.4.28"
jaxlib = "^0.4.28"
qiskit-dynamics = "^0.5.1"
qualang-tools = {path = "/workspaces/py-qua-tools", develop = true}

[tool.poetry.dev-dependencies]
black = "^22.3.0"
poethepoet = "^0.10.0"
flake8 = "^3.9.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.0"

[tool.black]
line-length = 120
target-version = ['py37']
#include = '(examples)/.+\.pyi?$'
#include = '(Quantum Control Applications)/.+\.pyi?$'
#include = '(Tutorials)/.+\.pyi?$'

[tool.poe.tasks]
format="black examples"
check_format="black --check ."

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
